#!/usr/bin/env python

import sys, re
from bs4 import BeautifulSoup
from os.path import dirname, abspath, join

EXTENSIONS = {
        "audio" : ("wav", "mp3", "mp2", "mpeg", "mpg", "mp4", "mpg4"),
        "img" : ("bmp", "gif", "jpg", "png", "mng", "jpeg"),
        "video" : ("mpg", "mpeg"),
        "text" : ("html", "htm")
}

def convert(ncl_file):
    ncl_code = open(ncl_file).read()
    soup = BeautifulSoup(ncl_code)
    apply_filters(soup, ncl_to_html, context_to_div, translate_medias)

    return soup.prettify()

def apply_filters(soup, *filters):
    [f(soup) for f in filters]

def ncl_to_html(soup):
    ncl = soup.find('ncl')
    ncl.name = 'html'

def context_to_div(soup):
    contexts = soup.find_all("context")
    for c in contexts:
        c.name = "div"

def translate_medias(soup):
    for media in soup.find_all('media'):
        for tag in EXTENSIONS.keys():
            if match(media, tag): media.name = tag

def match(m, media_type):
    return re.match(media_type + '(.*)', m.get('type', '')) or  \
           re.match('(.*)('+'|'.join(EXTENSIONS[media_type]) + ")", m['src'])

if __name__ == '__main__' and len(sys.argv) == 2:
    ncl_file = join(dirname(abspath(__file__)), sys.argv[1])
    print convert(ncl_file)
else:
    print "ncl2html - Convert your NCL documents to HTML"
    print "usage: ./ncl2html document.ncl"


