#!/usr/bin/env python

import sys
from bs4 import BeautifulSoup
from os.path import dirname, abspath, join
import re

EXTENSIONS = {
        "audio" : ("wav", "mp3", "mp2", "mpeg", "mpg", "mp4", "mpg4"),
        "image" : ("bpm", "gif", "jpg", "png"),
        "video" :  ("mpg", "mpeg")
}

def parse(ncl_file):
    ncl_code = open(ncl_file).read()
    soup = BeautifulSoup(ncl_code)

    ncl_to_html(soup)
    translate_medias(soup)

    return soup.prettify()

def ncl_to_html(soup):
    ncl = soup.find('ncl')
    ncl.name = 'html'
    return ncl

def translate_medias(soup):
    for media in soup.find_all('media'):
        if   match(media, "video"): media.name = "video"
        elif match(media, "image"): media.name = "image"
        elif match(media, "audio"): media.name = "audio"
        elif match(media, "text"): media.name = "html"


def match(m, media_type):
    return re.match(media_type + '(.*)', m.get('type', '')) or  \
           re.match('(.*)('+'|'.join(EXTENSIONS[media_type]) + ")", m['src'])

if __name__ == '__main__' and len(sys.argv) >= 2:
    ncl_file = join(dirname(abspath(__file__)), sys.argv[1])
    print parse(ncl_file)


